apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kafka-virtual-service
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - dev-kafka.consumer.svc.cluster.local
  tcp:
    - match:
        - port: {{.Values.kafkaPort}}
      route:
        - destination:
            host: dev-kafka.consumer.svc.cluster.local
            port:
              number: {{.Values.kafkaPort}}